import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Poppins } from "next/font/google";

const inter = Poppins( {subsets:["latin"], weight: ['100','200', '300', '400']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
        <body className={inter.className}>
          <Providers>
          {children}
          </Providers>
        </body>
    </html>
  );
}
